use_frameworks!

target 'MyGitHub' do
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'RxAlamofire'
    pod 'RxDataSources', '~> 1.0'
    pod 'Swinject', '~> 2.0.0'
    pod "RxGesture"
end


target 'MyGitHubTests' do
    pod 'RxSwift'
    pod 'RxCocoa'
end

